## Objectives for this Notebook    
* How to use the Keras library to build a regression model
* Download and clean the data set
* Build a neural network
* Train and test the network

In [1]:
import keras

<h2>Table of Contents</h2>


<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 4>
1. <a href="#Download-and-Clean-the-Data-Set">Download and Clean the Data Set</a><br>
2. <a href="#Import-Keras-Packages">Import Keras Packages</a><br>
3. <a href="#Build-a-Neural-Network">Build a Neural Network</a><br>
4. <a href="#Train-and-Test-the-Network">Train and Test the Network</a><br>  

</font>
</div>

In [2]:
import pandas as pd
import numpy as np 
import keras 

import warnings 
warnings.simplefilter("ignore",FutureWarning)

<strong>The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them. Ingredients include:</strong>

* Cement
* Blast furnace slag
* Fly ash
* Water
* Superplasticizer
* Coarse aggregate
* Fine aggregate

In [3]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

So the first concrete sample has 540 cubic meter of cement, 0 cubic meter of blast furnace slag, 0 cubic meter of fly ash, 162 cubic meter of water, 2.5 cubic meter of superplaticizer, 1040 cubic meter of coarse aggregate, 676 cubic meter of fine aggregate. Such a concrete mix which is 28 days old, has a compressive strength of 79.99 MPa.

In [4]:
concrete_data.shape

(1030, 9)

So, there are approximately 1000 samples to train our model on. Because of the few samples, we have to be careful not to overfit the training data.

In [6]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [8]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

The data looks pretty clean and is ready to be used to build our Model

#### Split data into predictors and target

The target variable in this problem is the concrete sample strength. Therefore, our predictors will be all the other columns.

In [9]:
concrete_data_columns = concrete_data.columns

In [11]:
predictors=concrete_data[concrete_data_columns[concrete_data_columns != 'Strength' ]]
target = concrete_data['Strength']

Let's do a quick sanity check of the predictors and the target dataframes

In [12]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [13]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

Finally, the last step is to normalize the data by substracting the mean and dividing by the standard deviation.

In [14]:
predictors_norm=(predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

Finally, the last step is to normalize the data by substracting the mean and dividing by the standard deviation.

In [15]:
n_cols=predictors_norm.shape[1] #number of predictors

In [16]:
from keras.models import Sequential
from keras.layers import Dense,Input

## Build a Neural Network

Let's define a function that defines our regression model for us so that we can conveniently call it to create our model.

In [20]:
def regression_model():

    #create model
    model=Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50,activation='relu'))
    model.add(Dense(50,activation='relu'))
    model.add(Dense(1))
    
    model.compile(optimizer='adam',loss='mean_squared_error')
    return model

The above function create a model that has two hidden layers, each of 50 hidden units.

## Train and Test the Network

Let's call the function now to create our model.

In [21]:
#build the model
model=regression_model()

In [22]:
model.fit(predictors_norm ,target,validation_split=0.3,epochs=100,verbose=2)

Epoch 1/100
23/23 - 2s - 77ms/step - loss: 1634.3572 - val_loss: 1124.3877
Epoch 2/100
23/23 - 0s - 7ms/step - loss: 1478.1246 - val_loss: 985.1884
Epoch 3/100
23/23 - 0s - 8ms/step - loss: 1233.0570 - val_loss: 783.3630
Epoch 4/100
23/23 - 0s - 7ms/step - loss: 889.6536 - val_loss: 545.2184
Epoch 5/100
23/23 - 0s - 7ms/step - loss: 538.1878 - val_loss: 347.9916
Epoch 6/100
23/23 - 0s - 7ms/step - loss: 312.5489 - val_loss: 249.5509
Epoch 7/100
23/23 - 0s - 7ms/step - loss: 243.3046 - val_loss: 214.7348
Epoch 8/100
23/23 - 0s - 7ms/step - loss: 223.8595 - val_loss: 197.2361
Epoch 9/100
23/23 - 0s - 7ms/step - loss: 210.8650 - val_loss: 187.6098
Epoch 10/100
23/23 - 0s - 7ms/step - loss: 200.1868 - val_loss: 185.4525
Epoch 11/100
23/23 - 0s - 7ms/step - loss: 191.7059 - val_loss: 179.4717
Epoch 12/100
23/23 - 0s - 8ms/step - loss: 184.8522 - val_loss: 174.8964
Epoch 13/100
23/23 - 0s - 8ms/step - loss: 179.3370 - val_loss: 171.6626
Epoch 14/100
23/23 - 0s - 7ms/step - loss: 174.3931 - val_loss: 171.7972
Epoch 15/100
23/23 - 0s - 7ms/step - loss: 170.7380 - val_loss: 167.0506
Epoch 16/100
23/23 - 0s - 9ms/step - loss: 167.0691 - val_loss: 165.6867
Epoch 17/100
23/23 - 0s - 7ms/step - loss: 163.4978 - val_loss: 165.1038
Epoch 18/100
23/23 - 0s - 8ms/step - loss: 160.6495 - val_loss: 164.3308
Epoch 19/100
23/23 - 0s - 7ms/step - loss: 158.2665 - val_loss: 163.5558
Epoch 20/100
23/23 - 0s - 7ms/step - loss: 155.7089 - val_loss: 163.6653
Epoch 21/100
23/23 - 0s - 7ms/step - loss: 153.5910 - val_loss: 164.1219
Epoch 22/100
23/23 - 0s - 7ms/step - loss: 151.2616 - val_loss: 162.3848
Epoch 23/100
23/23 - 0s - 8ms/step - loss: 150.1238 - val_loss: 162.6664
Epoch 24/100
23/23 - 0s - 8ms/step - loss: 148.3536 - val_loss: 163.2118
Epoch 25/100
23/23 - 0s - 7ms/step - loss: 146.8194 - val_loss: 161.7859
Epoch 26/100
23/23 - 0s - 8ms/step - loss: 144.5173 - val_loss: 164.4611
Epoch 27/100
23/23 - 0s - 7ms/step - loss: 142.8458 - val_loss: 162.6222
Epoch 28/100
23/23 - 0s - 8ms/step - loss: 140.9206 - val_loss: 164.0644
Epoch 29/100
23/23 - 0s - 7ms/step - loss: 139.8277 - val_loss: 162.9914
Epoch 30/100
23/23 - 0s - 8ms/step - loss: 138.3056 - val_loss: 162.9467
Epoch 31/100
23/23 - 0s - 7ms/step - loss: 136.2194 - val_loss: 161.9642
Epoch 32/100
23/23 - 0s - 9ms/step - loss: 134.7864 - val_loss: 161.8583
Epoch 33/100
23/23 - 0s - 14ms/step - loss: 133.8025 - val_loss: 162.0982
Epoch 34/100
23/23 - 0s - 7ms/step - loss: 132.1830 - val_loss: 164.2962
Epoch 35/100
23/23 - 0s - 7ms/step - loss: 130.3514 - val_loss: 164.4089
Epoch 36/100
23/23 - 0s - 8ms/step - loss: 128.5992 - val_loss: 161.8398
Epoch 37/100
23/23 - 0s - 7ms/step - loss: 127.4770 - val_loss: 160.1726
Epoch 38/100
23/23 - 0s - 8ms/step - loss: 125.6544 - val_loss: 160.1751
Epoch 39/100
23/23 - 0s - 7ms/step - loss: 123.7680 - val_loss: 161.7533
Epoch 40/100
23/23 - 0s - 7ms/step - loss: 122.4482 - val_loss: 160.4967
Epoch 41/100
23/23 - 0s - 7ms/step - loss: 120.2969 - val_loss: 160.1709
Epoch 42/100
23/23 - 0s - 7ms/step - loss: 119.1861 - val_loss: 158.5236
Epoch 43/100
23/23 - 0s - 8ms/step - loss: 116.6898 - val_loss: 160.4196
Epoch 44/100
23/23 - 0s - 7ms/step - loss: 114.8532 - val_loss: 158.9357
Epoch 45/100
23/23 - 0s - 7ms/step - loss: 112.9801 - val_loss: 157.1906
Epoch 46/100
23/23 - 0s - 7ms/step - loss: 110.6245 - val_loss: 157.9179
Epoch 47/100
23/23 - 0s - 8ms/step - loss: 109.0033 - val_loss: 158.1881
Epoch 48/100
23/23 - 0s - 8ms/step - loss: 105.8386 - val_loss: 153.3172
Epoch 49/100
23/23 - 0s - 7ms/step - loss: 103.2108 - val_loss: 151.9265
Epoch 50/100
23/23 - 0s - 8ms/step - loss: 100.6622 - val_loss: 153.6212
Epoch 51/100
23/23 - 0s - 7ms/step - loss: 97.7208 - val_loss: 148.2675
Epoch 52/100
23/23 - 0s - 8ms/step - loss: 95.8031 - val_loss: 150.8892
Epoch 53/100
23/23 - 0s - 8ms/step - loss: 92.9882 - val_loss: 145.0031
Epoch 54/100
23/23 - 0s - 7ms/step - loss: 89.6434 - val_loss: 146.7934
Epoch 55/100
23/23 - 0s - 8ms/step - loss: 87.1319 - val_loss: 141.1089
Epoch 56/100
23/23 - 0s - 7ms/step - loss: 83.8435 - val_loss: 139.1413
Epoch 57/100
23/23 - 0s - 7ms/step - loss: 81.9155 - val_loss: 140.2579
Epoch 58/100
23/23 - 0s - 8ms/step - loss: 78.5062 - val_loss: 135.2240
Epoch 59/100
23/23 - 0s - 6ms/step - loss: 76.1549 - val_loss: 143.9689
Epoch 60/100
23/23 - 0s - 6ms/step - loss: 73.0518 - val_loss: 129.7289
Epoch 61/100
23/23 - 0s - 7ms/step - loss: 72.9827 - val_loss: 141.8106
Epoch 62/100
23/23 - 0s - 5ms/step - loss: 69.3574 - val_loss: 135.4689
Epoch 63/100
23/23 - 0s - 5ms/step - loss: 65.9016 - val_loss: 133.8963
Epoch 64/100
23/23 - 0s - 5ms/step - loss: 64.4508 - val_loss: 128.5861
Epoch 65/100
23/23 - 0s - 5ms/step - loss: 62.2808 - val_loss: 130.2514
Epoch 66/100
23/23 - 0s - 6ms/step - loss: 60.7544 - val_loss: 127.4398
Epoch 67/100
23/23 - 0s - 5ms/step - loss: 59.4142 - val_loss: 124.7725
Epoch 68/100
23/23 - 0s - 5ms/step - loss: 57.8009 - val_loss: 124.9119
Epoch 69/100
23/23 - 0s - 5ms/step - loss: 56.2489 - val_loss: 122.9207
Epoch 70/100
23/23 - 0s - 5ms/step - loss: 54.4933 - val_loss: 124.6448
Epoch 71/100
23/23 - 0s - 7ms/step - loss: 53.9478 - val_loss: 129.2671
Epoch 72/100
23/23 - 0s - 5ms/step - loss: 51.0779 - val_loss: 114.6465
Epoch 73/100
23/23 - 0s - 6ms/step - loss: 51.6396 - val_loss: 118.8785
Epoch 74/100
23/23 - 0s - 6ms/step - loss: 49.1951 - val_loss: 129.9071
Epoch 75/100
23/23 - 0s - 5ms/step - loss: 48.4151 - val_loss: 127.9796
Epoch 76/100
23/23 - 0s - 5ms/step - loss: 47.3553 - val_loss: 126.8792
Epoch 77/100
23/23 - 0s - 6ms/step - loss: 45.7238 - val_loss: 117.4285
Epoch 78/100
23/23 - 0s - 5ms/step - loss: 44.3409 - val_loss: 130.6721
Epoch 79/100
23/23 - 0s - 5ms/step - loss: 44.0788 - val_loss: 119.3261
Epoch 80/100
23/23 - 0s - 5ms/step - loss: 42.7134 - val_loss: 122.5615
Epoch 81/100
23/23 - 0s - 5ms/step - loss: 42.2264 - val_loss: 116.2276
Epoch 82/100
23/23 - 0s - 5ms/step - loss: 41.3765 - val_loss: 119.0048
Epoch 83/100
23/23 - 0s - 8ms/step - loss: 40.3792 - val_loss: 118.0518
Epoch 84/100
23/23 - 0s - 5ms/step - loss: 40.3765 - val_loss: 116.5601
Epoch 85/100
23/23 - 0s - 5ms/step - loss: 39.5173 - val_loss: 116.2679
Epoch 86/100
23/23 - 0s - 5ms/step - loss: 38.6274 - val_loss: 124.3386
Epoch 87/100
23/23 - 0s - 5ms/step - loss: 38.6686 - val_loss: 119.8985
Epoch 88/100
23/23 - 0s - 5ms/step - loss: 37.9724 - val_loss: 126.5679
Epoch 89/100
23/23 - 0s - 5ms/step - loss: 37.6136 - val_loss: 119.1248
Epoch 90/100
23/23 - 0s - 5ms/step - loss: 37.0627 - val_loss: 116.6161
Epoch 91/100
23/23 - 0s - 5ms/step - loss: 36.3993 - val_loss: 116.5710
Epoch 92/100
23/23 - 0s - 5ms/step - loss: 35.7237 - val_loss: 112.5303
Epoch 93/100
23/23 - 0s - 5ms/step - loss: 35.6649 - val_loss: 112.3759
Epoch 94/100
23/23 - 0s - 5ms/step - loss: 34.9257 - val_loss: 123.8078
Epoch 95/100
23/23 - 0s - 5ms/step - loss: 34.7005 - val_loss: 120.6654
Epoch 96/100
23/23 - 0s - 5ms/step - loss: 34.1651 - val_loss: 121.4328
Epoch 97/100
23/23 - 0s - 5ms/step - loss: 34.0043 - val_loss: 117.5823
Epoch 98/100
23/23 - 0s - 5ms/step - loss: 33.9367 - val_loss: 118.9915
Epoch 99/100
23/23 - 0s - 5ms/step - loss: 32.9721 - val_loss: 119.3698
Epoch 100/100
23/23 - 0s - 5ms/step - loss: 32.7715 - val_loss: 119.8175